import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import "../App.css";

const STR_TRANSLATIONS = {
  en: {
    title: "Suspicious Transaction Report",
    sec1: "Transaction Information",
    sec2: "Risk Signal Evidence",
    sec3: "Supporting Evidence",
    sec4: "Investigation Explanation",
    lblTxId: "Transaction ID",
    lblAmount: "Amount",
    lblScore: "Risk Score",
    lblBand: "Risk Band",
    lblDate: "Transaction Date",
    lblAction: "Recommended Action",
    lblAF: "Adaptive Friction (45%)",
    lblFF: "Fund Flow (35%)",
    lblPH: "Phishing (20%)",
    genBy: "Report generated by UFDE",
    close: "Close",
    fullReport: "📄 Full Report",
    downloadPdf: "📥 Download PDF",
  },
  fr: {
    title: "DÉCLARATION DE SOUPÇON (STR)",
    sec1: "Informations sur la Transaction",
    sec2: "Preuves des Signaux de Risque",
    sec3: "Preuves et Explications",
    sec4: "Explication de l'Enquête",
    lblTxId: "Identifiant Transaction",
    lblAmount: "Montant",
    lblScore: "Score de Risque Consolidé",
    lblBand: "Niveau de Risque",
    lblDate: "Date de Transaction",
    lblAction: "Action Recommandée",
    lblAF: "Friction Adaptative (45%)",
    lblFF: "Flux de Fonds (35%)",
    lblPH: "Site de Hameçonnage (20%)",
    genBy: "Rapport généré par UFDE",
    close: "Fermer",
    fullReport: "📄 Rapport Complet",
    downloadPdf: "📥 Télécharger le PDF",
  },
  hi: {
    title: "संदेहास्पद लेन-देन रिपोर्ट (STR)",
    sec1: "लेन-देन की जानकारी",
    sec2: "जोखिम संकेत साक्ष्य",
    sec3: "सहायक साक्ष्य",
    sec4: "जांच का स्पष्टीकरण",
    lblTxId: "लेन-देन आईडी",
    lblAmount: "राशि",
    lblScore: "समेकित जोखिम स्कोर",
    lblBand: "जोखिम श्रेणी",
    lblDate: "लेन-देन तिथि",
    lblAction: "अनुशंसित कार्रवाई",
    lblAF: "अनुकूली घर्षण (45%)",
    lblFF: "फंड प्रवाह (35%)",
    lblPH: "फ़िशिंग (20%)",
    genBy: "UFDE द्वारा उत्पन्न रिपोर्ट",
    close: "बंद करें",
    fullReport: "📄 पूरी रिपोर्ट",
    downloadPdf: "📥 पीडीएफ डाउनलोड करें",
  },
};

function translateRiskBand(band, lang) {
  if (lang === "fr") {
    if (band === "Critical") return "Critique";
    if (band === "High") return "Élevé";
    if (band === "Medium") return "Moyen";
    if (band === "Low") return "Faible";
    if (band === "Very Low") return "Très Faible";
  } else if (lang === "hi") {
    if (band === "Critical") return "गंभीर";
    if (band === "High") return "उच्च";
    if (band === "Medium") return "मध्यम";
    if (band === "Low") return "कम";
    if (band === "Very Low") return "बहुत कम";
  }
  return band;
}

function translateAction(action, lang) {
  if (lang === "fr") {
    if (action.includes("Immediate hold") || action.includes("Investigation")) return "Blocage immédiat de la transaction. Enquête de l'analyste et préparation du STR.";
    if (action.includes("Analyst-level review")) return "Examen de niveau analyste – transmettre le dossier au rôle Analyste.";
    if (action.includes("Automated monitoring") || action.includes("Monitoring")) return "Surveillance automatisée – marquer la transaction pour suivi.";
  } else if (lang === "hi") {
    if (action.includes("Immediate hold") || action.includes("Investigation")) return "लेन-देन पर तत्काल रोक। विश्लेषक जांच और ड्राफ्ट STR जनरेट करें।";
    if (action.includes("Analyst-level review")) return "विश्लेषक-स्तरीय समीक्षा - मामले को विश्लेषक भूमिका को भेजें।";
    if (action.includes("Automated monitoring") || action.includes("Monitoring")) return "स्वचालित निगरानी - वॉच-लिस्ट स्थिति के लिए लेन-देन को चिह्नित करें।";
  }
  return action;
}

function translateExplanationText(text, lang) {
  if (!text) return text;
  if (lang === "fr") {
    return text
      .replace("Device fingerprint differs from the stored profile.", "L'empreinte de l'appareil diffère du profil enregistré.")
      .replace("Transaction originated from a distant location.", "La transaction provient d'un emplacement distant.")
      .replace("Transaction amount is higher than the historic mean.", "Le montant de la transaction est supérieur à la moyenne historique.")
      .replace("Fund flow shows an imbalance between incoming and outgoing connections.", "Le flux de fonds montre un déséquilibre entre les connexions entrantes et sortantes.")
      .replace("Remaining balance is low compared with the total amount sent.", "Le solde restant est faible par rapport au montant total envoyé.")
      .replace("Funds were held for less than 60 minutes.", "Les fonds ont été détenus pendant moins de 60 minutes.")
      .replace("Domain is relatively new.", "Le domaine est relativement récent.")
      .replace("Certificate is self-signed or has less than 30 days of validity.", "Le certificat est auto-signé ou a moins de 30 jours de validité.")
      .replace("Domain appears on the local blacklist.", "Le domaine apparaît sur la liste noire locale.");
  } else if (lang === "hi") {
    return text
      .replace("Device fingerprint differs from the stored profile.", "डिवाइस फिंगरप्रिंट संग्रहीत प्रोफ़ाइल से भिन्न है।")
      .replace("Transaction originated from a distant location.", "लेन-देन दूरस्थ स्थान से उत्पन्न हुआ।")
      .replace("Transaction amount is higher than the historic mean.", "लेन-देन की राशि ऐतिहासिक औसत से अधिक है।")
      .replace("Fund flow shows an imbalance between incoming and outgoing connections.", "फंड प्रवाह आने वाले और जाने वाले कनेक्शनों के बीच असंतुलन दिखाता है।")
      .replace("Remaining balance is low compared with the total amount sent.", "भेजी गई कुल राशि की तुलना में शेष राशि कम है।")
      .replace("Funds were held for less than 60 minutes.", "फंड 60 मिनट से कम समय के लिए रखे गए थे।")
      .replace("Domain is relatively new.", "डोमेन अपेक्षाकृत नया है।")
      .replace("Certificate is self-signed or has less than 30 days of validity.", "प्रमाणपत्र स्व-हस्ताक्षरित है या वैधता 30 दिनों से कम है।")
      .replace("Domain appears on the local blacklist.", "डोमेन स्थानीय ब्लैकलिस्ट पर दिखाई देता है।");
  }
  return text;
}


function TransactionDetail({ transaction, role, onBack }) {

  const [showEdit, setShowEdit] = useState(false);
  const [showSTR, setShowSTR] = useState(false);
  const [reportLang, setReportLang] = useState("en");

  const t = STR_TRANSLATIONS[reportLang] || STR_TRANSLATIONS.en;

  // =====================================================
  // MAP REAL BACKEND FIELDS
  // =====================================================

  // Real explanations from backend
  const rawExplanations = Array.isArray(transaction.explanations) && transaction.explanations.length > 0
    ? transaction.explanations
    : ["No explanation was returned by the backend for this transaction."];

  const explanations = rawExplanations.map(e => translateExplanationText(e, reportLang));

  const hasMissingData = transaction.hasMissingData || transaction.score === null || transaction.score === undefined ||
    rawExplanations.some(e => typeof e === "string" && e.toLowerCase().includes("missing data"));

  const totalScore = hasMissingData ? null : Math.round(Number(transaction.score ?? 0));
  const rawRiskBand = hasMissingData ? "Critical" : (transaction.band || "Very Low");
  const riskBand = translateRiskBand(rawRiskBand, reportLang);

  // Real individual scores from backend
  const afScore = transaction.adaptiveScore != null ? Math.round(Number(transaction.adaptiveScore)) : null;
  const ffScore = transaction.fundFlowScore != null ? Math.round(Number(transaction.fundFlowScore)) : null;
  const phScore = transaction.phishingScore != null ? Math.round(Number(transaction.phishingScore)) : null;

  // Recommended action
  const rawRecommendedAction = transaction.recommendedAction ||
    (hasMissingData ? "Invalid or Missing Data - Manual Review Required" : (rawRiskBand === "Critical" || rawRiskBand === "High" ? "Further Investigation" : "Continue Monitoring"));
  
  const recommendedAction = translateAction(rawRecommendedAction, reportLang);

  // Weighted contributions
  const afContrib = afScore != null ? (afScore * 0.45).toFixed(1) : "N/A";
  const ffContrib = ffScore != null ? (ffScore * 0.35).toFixed(1) : "N/A";
  const phContrib = phScore != null ? (phScore * 0.20).toFixed(1) : "N/A";

  // Fund flow nodes
  const flowNodes = [
    { name: "Source Account", value: transaction.id ? `ACC-${transaction.id.replace(/\D/g, "").slice(0, 4) || "0000"}` : "ACC-SRC" },
    { name: "Intermediate",   value: "ACC-5831" },
    { name: "Merchant",       value: "MER-2098" },
    { name: "Destination",    value: `ACC-${Math.floor(Math.random() * 9000 + 1000)}` },
  ];

  function getRiskClass() {
    return rawRiskBand.toLowerCase().replace(" ", "-");
  }

  useEffect(() => {
    const open = showEdit || showSTR;
    document.body.classList.toggle("ufde-modal-open", open);
    return () => document.body.classList.remove("ufde-modal-open");
  }, [showEdit, showSTR]);

  function downloadTransaction() {
    if (role !== "admin") return;
    const data = {
      transactionId: transaction.id,
      amount: transaction.amount,
      currency: transaction.currency || "INR",
      riskScore: totalScore,
      hasMissingData,
      riskBand,
      recommendedAction,
      formula: "0.45 × AF + 0.35 × FF + 0.20 × PH",
      signals: { adaptiveFriction: afScore, fundFlow: ffScore, phishing: phScore },
      weightedContributions: { af: afContrib, ff: ffContrib, ph: phContrib },
      explanations,
      generatedAt: new Date().toISOString(),
    };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${transaction.id}-investigation.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  function openOfficialReport() {
    const txId = transaction.id || transaction.transactionId || transaction.dbId;
    window.open(`/api/reports/str/${txId}?lang=${reportLang}`, "_blank");
  }

  async function downloadPdfReport() {
    const txId = transaction.id || transaction.transactionId || transaction.dbId;
    try {
      const res = await fetch(`/api/reports/str/${txId}?lang=${reportLang}`);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const htmlText = await res.text();

      const parser = new DOMParser();
      const doc = parser.parseFromString(htmlText, "text/html");
      const card = doc.querySelector(".card");

      const tempDiv = document.createElement("div");
      tempDiv.style.cssText = "position: absolute; left: 0; top: 0; width: 800px; background: #ffffff; color: #000000; z-index: -9999; opacity: 1; padding: 25px;";

      if (card) {
        const langBar = card.querySelector(".lang-bar");
        if (langBar) langBar.style.display = "none";
        tempDiv.appendChild(card);
      } else {
        tempDiv.innerHTML = htmlText;
      }
      document.body.appendChild(tempDiv);

      try {
        const { default: h2p } = await import("html2pdf.js");
        const opt = {
          margin: 10,
          filename: `STR-Report-${txId}-${reportLang.toUpperCase()}.pdf`,
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2, useCORS: true, logging: false, scrollX: 0, scrollY: 0 },
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
        };
        await h2p().set(opt).from(tempDiv).save();
      } catch (err) {
        console.error("html2pdf failed:", err);
        const printWindow = window.open("", "_blank");
        if (printWindow) {
          printWindow.document.write(htmlText);
          printWindow.document.close();
          printWindow.focus();
          setTimeout(() => printWindow.print(), 800);
        }
      } finally {
        if (document.body.contains(tempDiv)) {
          document.body.removeChild(tempDiv);
        }
      }
    } catch (err) {
      console.error("PDF error:", err);
      window.open(`/api/reports/str/${txId}?lang=${reportLang}`, "_blank");
    }
  }

  return (
    <div className="transaction-detail-panel">

      <div className="transaction-detail-header">
        <div>
          <h2>Transaction Details</h2>
          <p>ID: {transaction.id}</p>
        </div>
        <button onClick={onBack} aria-label="Back to transactions">×</button>
      </div>

      <div className="compact-risk-summary-card">
        <div className="compact-score-display">
          <div className="compact-score-circle">
            {hasMissingData ? (
              <span className="compact-score-number" style={{ color: "#dc2626", fontSize: "18px" }}>N/A</span>
            ) : (
              <>
                <span className="compact-score-number">{totalScore}</span>
                <span className="compact-score-denom">/100</span>
              </>
            )}
          </div>
          <div>
            <span className={`risk-badge ${getRiskClass()}`}>{riskBand}</span>
            <p className="compact-score-meta">
              Date: <strong>{transaction.date}</strong>
            </p>
          </div>
        </div>

        <div className="compact-info-grid">
          <div>
            <label>Amount</label>
            <strong>₹{Number(transaction.amount || 0).toLocaleString("en-IN")}</strong>
          </div>
          <div>
            <label>Status</label>
            <strong>{transaction.status || "Completed"}</strong>
          </div>
          <div>
            <label>Action</label>
            <strong>{recommendedAction}</strong>
          </div>
        </div>
      </div>

      <section className="compact-detail-section">
        <div className="compact-section-heading">
          <h3>Risk Signals</h3>
          <p>Weighted breakdown of detection engines:</p>
        </div>

        <div className="compact-signal-grid">
          <div className="compact-signal-card">
            <div className="compact-signal-header">
              <span className="compact-signal-title">Adaptive Friction</span>
              <span className="compact-weight-badge">45%</span>
            </div>
            <div className="compact-signal-score">{afScore != null ? `${afScore} / 100` : "N/A (Missing)"}</div>
            <p className="compact-signal-meta">Weighted contribution: <strong>{afContrib}</strong></p>
          </div>

          <div className="compact-signal-card">
            <div className="compact-signal-header">
              <span className="compact-signal-title">Fund Flow</span>
              <span className="compact-weight-badge">35%</span>
            </div>
            <div className="compact-signal-score">{ffScore != null ? `${ffScore} / 100` : "N/A (Missing)"}</div>
            <p className="compact-signal-meta">Weighted contribution: <strong>{ffContrib}</strong></p>
          </div>

          <div className="compact-signal-card">
            <div className="compact-signal-header">
              <span className="compact-signal-title">Phishing</span>
              <span className="compact-weight-badge">20%</span>
            </div>
            <div className="compact-signal-score">{phScore != null ? `${phScore} / 100` : "N/A (Missing)"}</div>
            <p className="compact-signal-meta">Weighted contribution: <strong>{phContrib}</strong></p>
          </div>
        </div>
      </section>

      <section className="compact-detail-section">
        <div className="compact-section-heading">
          <h3>Explanations</h3>
          <p>Engine triggers for this score:</p>
        </div>
        <div className="compact-explanations-list">
          {explanations.map((exp, idx) => (
            <div key={idx} className="compact-explanation-item">
              <span>•</span>
              <p>{exp}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="compact-detail-section">
        <div className="compact-section-heading">
          <h3>Fund Flow Map</h3>
          <p>Entity transfer sequence:</p>
        </div>
        <div className="compact-flow-list">
          {flowNodes.map((node, i) => (
            <div key={i} className="compact-flow-item">
              <div className="compact-flow-node">
                <span>{node.name}</span>
                <strong>{node.value}</strong>
              </div>
              {i < flowNodes.length - 1 && (
                <div className="compact-flow-arrow">↓</div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* REPORT LANGUAGE SELECTOR */}
      {(role === "admin" || role === "analyzer") && (
        <section className="compact-detail-section" style={{ marginTop: 12 }}>
          <div className="compact-section-heading">
            <h3>Report Language</h3>
            <p>Select output language for STR:</p>
          </div>
          <div style={{ display: "flex", gap: "8px", marginTop: "8px" }}>
            {[
              { code: "en", label: "🇬🇧 English" },
              { code: "fr", label: "🇫🇷 Français" },
              { code: "hi", label: "🇮🇳 हिंदी" },
            ].map(({ code, label }) => (
              <button
                key={code}
                className="secondary-action compact-action"
                style={{
                  flex: 1,
                  backgroundColor: reportLang === code ? "#1e3a8a" : undefined,
                  color: reportLang === code ? "#fff" : undefined,
                  borderColor: reportLang === code ? "#1e3a8a" : undefined,
                }}
                onClick={() => setReportLang(code)}
              >
                {label}
              </button>
            ))}
          </div>
        </section>
      )}

      {/* ADMIN ACTIONS */}
      {role === "admin" && (
        <section className="compact-detail-actions">
          <button className="secondary-action compact-action" onClick={() => setShowEdit(true)}>
            Edit
          </button>
          <button className="secondary-action compact-action" onClick={downloadTransaction}>
            ↓ JSON
          </button>
          <button className="primary-action compact-action" onClick={() => setShowSTR(true)}>
            STR
          </button>
          <button className="secondary-action compact-action" onClick={downloadPdfReport}>
            📥 PDF
          </button>
        </section>
      )}

      {role === "analyzer" && (
        <section className="compact-detail-actions">
          <button className="primary-action compact-action" onClick={() => setShowSTR(true)}>
            STR
          </button>
          <button className="secondary-action compact-action" onClick={openOfficialReport}>
            📄 View Report
          </button>
        </section>
      )}

      {/* EDIT MODAL */}
      {showEdit && createPortal(
        <div
          className="modal-overlay edit-overlay"
          style={{ zIndex: 9999999 }}
          onMouseDown={(e) => { if (e.target === e.currentTarget) setShowEdit(false); }}
        >
          <div className="settings-modal edit-modal" onMouseDown={(e) => e.stopPropagation()}>
            <div className="settings-header">
              <div>
                <span className="str-small-label">TRANSACTION UPDATE</span>
                <h2>Edit Transaction</h2>
              </div>
              <button onClick={() => setShowEdit(false)} aria-label="Close edit">×</button>
            </div>
            <div className="edit-form">
              <label>Transaction ID</label>
              <input value={transaction.id} readOnly />
              <label>Amount</label>
              <input defaultValue={transaction.amount} type="number" />
              <p className="edit-warning">
                Risk score is calculated by the detection engine and cannot be directly edited.
              </p>
            </div>
            <div className="edit-actions">
              <button className="secondary-action" onClick={() => setShowEdit(false)}>Cancel</button>
              <button
                className="primary-action"
                onClick={() => {
                  alert("Transaction update will be sent to the backend.");
                  setShowEdit(false);
                }}
              >
                Save Changes
              </button>
            </div>
          </div>
        </div>,
        document.body
      )}

      {/* STR MODAL WITH REAL-TIME TRANSLATION */}
      {showSTR && createPortal(
        <div
          className="modal-overlay str-overlay"
          style={{ zIndex: 9999999 }}
          onMouseDown={(e) => { if (e.target === e.currentTarget) setShowSTR(false); }}
        >
          <div
            className="settings-modal str-modal"
            onMouseDown={(e) => e.stopPropagation()}
          >
            {/* STR HEADER */}
            <div className="settings-header str-header">
              <div>
                <span className="str-small-label">UFDE REPORT</span>
                <h2>{t.title}</h2>
              </div>
              <button className="str-close-button" onClick={() => setShowSTR(false)} aria-label="Close STR">×</button>
            </div>

            {/* STR SCROLLABLE CONTENT */}
            <div className="str-scroll-content">
              {/* Section 1 */}
              <div className="str-section">
                <h3>{t.sec1}</h3>
                <div className="str-info-grid">
                  <div className="str-info-item"><span>{t.lblTxId}</span><strong>{transaction.id}</strong></div>
                  <div className="str-info-item"><span>{t.lblAmount}</span><strong>₹{Number(transaction.amount || 0).toLocaleString("en-IN")}</strong></div>
                  <div className="str-info-item"><span>{t.lblScore}</span><strong>{totalScore} / 100</strong></div>
                  <div className="str-info-item">
                    <span>{t.lblBand}</span>
                    <span className={`risk-badge ${getRiskClass()}`}>{riskBand}</span>
                  </div>
                  <div className="str-info-item"><span>{t.lblDate}</span><strong>{transaction.date}</strong></div>
                  <div className="str-info-item"><span>{t.lblAction}</span><strong>{recommendedAction}</strong></div>
                </div>
              </div>

              {/* Section 2 */}
              <div className="str-section">
                <h3>{t.sec2}</h3>
                <div className="str-signal-list">
                  <div className="str-signal-row">
                    <div><span className="str-signal-code">AF</span><strong>{t.lblAF}</strong></div>
                    <strong>{afScore} / 100 → {afContrib}</strong>
                  </div>
                  <div className="str-signal-row">
                    <div><span className="str-signal-code">FF</span><strong>{t.lblFF}</strong></div>
                    <strong>{ffScore} / 100 → {ffContrib}</strong>
                  </div>
                  <div className="str-signal-row">
                    <div><span className="str-signal-code">PH</span><strong>{t.lblPH}</strong></div>
                    <strong>{phScore} / 100 → {phContrib}</strong>
                  </div>
                </div>
              </div>

              {/* Section 3 */}
              <div className="str-section">
                <h3>{t.sec3}</h3>
                <div className="str-evidence-list">
                  {explanations.map((e, i) => (
                    <div className="str-evidence-item" key={i}>
                      <span>•</span>
                      <p>{e}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Section 4 */}
              <div className="str-section">
                <h3>{t.sec4}</h3>
                <p className="str-explanation">
                  {reportLang === "fr" ? (
                    `La transaction ${transaction.id} a obtenu un score de ${totalScore}/100 (${riskBand}). La friction adaptative a contribué pour ${afContrib}, le flux de fonds pour ${ffContrib} et la détection de phishing pour ${phContrib} au score de risque consolidé. Action recommandée: ${recommendedAction}.`
                  ) : reportLang === "hi" ? (
                    `लेन-देन ${transaction.id} ने ${totalScore}/100 (${riskBand}) का स्कोर प्राप्त किया। अनुकूली घर्षण ने ${afContrib}, फंड प्रवाह ने ${ffContrib}, और फ़िशिंग पहचान ने ${phContrib} का योगदान दिया। अनुशंसित कार्रवाई: ${recommendedAction}।`
                  ) : (
                    `Transaction ${transaction.id} scored ${totalScore}/100 (${riskBand}). Adaptive Friction contributed ${afContrib}, Fund Flow contributed ${ffContrib}, and Phishing detection contributed ${phContrib} to the consolidated risk score. Recommended action: ${recommendedAction}.`
                  )}
                </p>
              </div>

              <div className="str-generated-info">
                <span>{t.genBy}</span>
                <span>{new Date().toLocaleString("en-IN")}</span>
              </div>
            </div>

            {/* STR FOOTER */}
            <div className="str-footer">
              <div style={{ display: "flex", gap: "6px", alignItems: "center", flex: 1 }}>
                {[{ code: "en", label: "EN" }, { code: "fr", label: "FR" }, { code: "hi", label: "HI" }].map(({ code, label }) => (
                  <button
                    key={code}
                    className="secondary-action"
                    style={{
                      padding: "4px 10px",
                      fontSize: "12px",
                      backgroundColor: reportLang === code ? "#1e3a8a" : undefined,
                      color: reportLang === code ? "#fff" : undefined,
                    }}
                    onClick={() => setReportLang(code)}
                  >
                    {label}
                  </button>
                ))}
              </div>

              <button className="secondary-action" onClick={() => setShowSTR(false)}>
                {t.close}
              </button>

              <button className="secondary-action" onClick={openOfficialReport}>
                {t.fullReport}
              </button>

              <button className="primary-action" onClick={downloadPdfReport}>
                {t.downloadPdf}
              </button>
            </div>
          </div>
        </div>,
        document.body
      )}

    </div>
  );
}

export default TransactionDetail;
